language: node_js
node_js: stable
sudo: required
dist: trusty
jobs:
  include:
    - stage: frontend_CI
      name: "Frontend tests"
      before_install: cd frontend
      script:
        - npm run test
        - npm run build